version: 0.2

phases:
  install:
    runtime-version:
      java: correto11
      docker: 19
    build:
      commands:
        - echo Build started on 'date'
        - mvn clean package

artifacts:
  files:
    - service/target/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'