#=======================================================================================================================
#   SPRING
#=======================================================================================================================
spring:
  datasource:
    url: jdbc:mysql://database-1.cfmsle0fz4hd.sa-east-1.rds.amazonaws.com:3306/bluemeet?serverTimezone=UTC&useSSL=false
    username: admin